In [1]:
#Write a Python program that declares variables of different data types (e.g., string, integer, float,and boolean). Output the variables in a sentence format using print() and f-strings.

name="Tom"
age=21
height=5.9
is_student=True
print(f"My name is {name}, I am {age} years old, my height is {height} feet, and it is {is_student} that I am a student.")

My name is Tom, I am 21 years old, my height is 5.9 feet, and it is True that I am a student.


In [4]:
#5.Write a Python program that takes an integer input and checks whether the number is positive,negative, or zero using conditional statements (if-else).

n=5
if n>0:
    print("The number is positive.")
elif n<0:
    print("The number is negative.")
else:
    print("The number is zero.")

The number is positive.


In [6]:
#6.Write a Python program that takes a number as input and prints the multiplication tablefor that number (from 1 to 10)

n=5
for i in range(1,11):
    print(n,"x",i,"=",n*i)

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [7]:
"""7.Create a Python list that contains the names of 5 different fruits. Perform the given operations on
the list"""
fruits=["apple","banana","cherry","date","elderberry"]
fruits.append("fig")
fruits.remove("banana")
fruits[2]="grape"
fruits.sort()
fruits.reverse()
print(fruits)

['grape', 'fig', 'elderberry', 'cherry', 'apple']


In [8]:
#8.Write a Python program that creates a tuple containing 5 numbers. Perform the given operations on the tuple

numbers=(1,2,3,4,5)
numbers+= (6,)
print(numbers)

(1, 2, 3, 4, 5, 6)


In [10]:
#9.Create a dictionary that stores the names of 3 students as keys and their marks in mathematics as values. Perform the given operations.

students={"Rina":99,"Riya":90,"Maxie":78}
students["Maxie"]=92
del students["Riya"]
students["Rina"]=99
print(students)

{'Rina': 99, 'Maxie': 92}


In [12]:
#10.Create two sets of integers. Perform the given set operations

set1={1,2,3,4,5}
set2={4,5,6,7,8}
set3=set1.union(set2)
set4=set1.intersection(set2)
set5=set1.difference(set2)
print(set3,set4,set5)

{1, 2, 3, 4, 5, 6, 7, 8} {4, 5} {1, 2, 3}


In [13]:
#11.Write a Python function called find_largest() that takes a list of numbers as input and returns the largest number from the list. Test the function with a sample list

def find_largest(nums):return max(nums)
nums=[3,5,7,2,8]
print(find_largest(nums))

8


In [16]:
#12.Use list comprehension to create a list of squares of all even numbers between 1 and 20

squares=[x**2 for x in range(1,21) if x%2==0]
print(squares)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [18]:
#13. Write a Python script that uses a lambda function to calculate the product of two numbers provided by the user

product=lambda x,y:x*y
x=5
y=4
print(product(x,y))

20


In [20]:
#14. Write a Python program to create a one-dimensional, two-dimensional, and three-dimensional NumPy array.Print the shape and dimensions of each array

import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1.shape,arr1.ndim)
print(arr2.shape,arr2.ndim)
print(arr3.shape,arr3.ndim)

(5,) 1
(2, 3) 2
(2, 2, 2) 3


In [22]:
#15. Write a Python program to create a 5x5 NumPy array of random integers and Perform array indexing as given

import numpy as np
arr=np.random.randint(1,100,(5,5))
print(arr)
print(arr[2,3])
print(arr[1:4,1:4])

[[73 66 98 35 62]
 [55 60 59 16 14]
 [65  5 61 55 80]
 [38 35 82 12 72]
 [89 97 16 70 56]]
55
[[60 59 16]
 [ 5 61 55]
 [35 82 12]]


In [24]:
#16. create a NumPy array of shape (4, 4) containing numbers from 1 to 16. Use slicing to extract for the given conditions

import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr)
print(arr[1:3,1:3])
print(arr[:2,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]
[[1 2]
 [5 6]]


In [26]:
#17. Write a Python program that creates a 2D array of shape (6, 2) using np.arange() and then reshapes it into a 3D array of shape (2, 3, 2). Flatten the reshaped array and print the result.

import numpy as np
arr=np.arange(12).reshape(6,2)
arr_3d=arr.reshape(2,3,2)
arr_flat=arr_3d.flatten()
print(arr_flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
#18. Write a Python program to demonstrate broadcasting. Create an array of shape (3, 3) and add a one-dimensional array of shape (1, 3) to it using broadcasting.

import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([1,1,1])
result=arr1+arr2
print(result)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [31]:
"""19. Create two NumPy arrays of the same shape, A and B. Perform the following arithmetic operations:
Element-wise addition.
Element-wise subtraction.
Element-wise multiplication.
Element-wise division"""

import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
add=A+B
sub=A-B
mul=A*B
div=A/B
print(add)
print(sub)
print(mul)
print(div)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [34]:
"""20. Create a Pandas DataFrame with the given Name and marks of 3 courses:
Add a new column named 'Total' that represents the sum of all the courses. Add 'Grade' based
on the values of the 'Total'. Print the updated DataFrame with the new 'Total' and 'Grade'
column"""

import pandas as pd
data={'Name': ['Aarav','Isha','Vihaan'],'Maths':[85,90,78],'Science':[88,92,85],'English':[80,85,88]}
df=pd.DataFrame(data)
df['Total']=df['Maths']+df['Science']+df['English']
df['Grade']=df['Total'].apply(lambda x: 'A' if x>=250 else ('B' if x>=200 else 'C'))
print(df)

     Name  Maths  Science  English  Total Grade
0   Aarav     85       88       80    253     A
1    Isha     90       92       85    267     A
2  Vihaan     78       85       88    251     A
